export default toast to reuse them with custom props.
calintamas/react-native-toast-message pull request #225
Opened 2021-07-23 13:44 UTC by MrLibya

Hello,
I want to use the default toast layout but with small changes so instead of re-create the layout I want to use the old one and just override the props.

2021-09-09 05:26 UTC, CalebLovell commented
I second this PR! Can this be merged? I realized today there is no way to just extend the existing components, you have to remake it yourself. I would really just like to increase the font size of the text and leave the rest as is, but right now there is no way to do that. This PR would basically fix that...

2021-09-09 11:51 UTC, calintamas requested changes
@MrLibya Thanks for your contribution! I've added a few small comments, nothing major

2021-09-09 11:51 UTC, calintamas commented on README.md
> +You can either use the default `BaseToast` style and adjust its layout, or create Toast layouts from scratch or reuse the default layout
Can you adjust the wording please?

```suggestion
You can either use any of the default `BaseToast`, `SuccessToast`, `ErrorToast` or `InfoToast` components and adjust their layout, or create Toast layouts from scratch.
```

2021-09-09 11:51 UTC, calintamas commented on README.md
> +
Here as well

```suggestion
   /*
    Reuse the default ErrorToast toast component
  */
  error: (props) => (
    <ErrorToast 
      {...props}
      text1Style={{
        fontSize: 17
      }}
      text2Style={{
        fontSize: 15
      }}
    />
  ),
```

2021-09-09 11:51 UTC, calintamas commented on index.js
> +export { default as InfoToast } from './src/components/info';
If we are to do this, the type definition file would need to be updated as well
https://github.com/calintamas/react-native-toast-message/blob/master/index.d.ts

2021-09-09 11:52 UTC, calintamas commented
> I second this PR! Can this be merged? I realized today there is no way to just extend the existing components, you have to remake it yourself. I would really just like to increase the font size of the text and leave the rest as is, but right now there is no way to do that. This PR would basically fix that...

@CalebLovell Yes, the type definition file needs to be updated before I can merge, but other than that, all good

2021-09-09 22:37 UTC, MrLibya commented
@calintamas 
I've updated the type as well, tbh I dunno if it could be done in another way so plz check it :)

2021-09-10 05:59 UTC, calintamas approved these changes
Looks good, thanks!

2021-09-10 05:59 UTC, calintamas commented
Tests workflow failing due to coveralls issue (all tests pass), I'll merge

2021-09-10 06:00 UTC, merged

2021-09-22 23:41 UTC, CalebLovell commented
Thanks for doing this, added it today to our app and it works great!